import Item from '../../components/Item'
import Head from 'next/head'

export default function Food({ items }) {
  return (
    <div>
        <Head>
          <title>Item | Inventory App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h2>Item List</h2>
        {items.map((item) => (
          <Item item={item} key={item.id}  />
        ))}
    </div>
  )
}

/**
* 
* @param {import('next').GetServerSidePropsContext} context
* @returns
*/
export async function getServerSideProps(context) {
    const res = await fetch('http://localhost:3000/api/item')
    const items = await res.json()

    return {
        props: {
           items
        }
    }
}